### ISSUE TITLE
Default Modal used in Method CommonBase GridUtilities

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/my-recent-items#6]
The method 'CommonBase GridUtilities' uses 'DefaultModal' for calling Forms. This function is depracted. Currently this does not seem to be a problem. I am not sure if the methods are actually called anywhere.

**Comment by AngelaIp** [comment]
PR [#9](https://github.com/ArasLabs/my-recent-items/pull/9) solves this one.

**Comment by sampoearas** [comment]
PR #9 merged successfully.
